# Headnode Server Configuration

# API authentication
api_key: "your-secure-api-key"

# Server configuration
host: "0.0.0.0"
port: 5001
debug: True

# Worker node configuration
worker_nodes:
  - host: "ec2-18-222-202-30.us-east-2.compute.amazonaws.com"
    port: 5000
    api_key: "your-secure-api-key"
    
  - host: "ec2-3-20-205-97.us-east-2.compute.amazonaws.com"
    port: 5000
    api_key: "your-secure-api-key"
    
  - host: "ec2-18-118-215-217.us-east-2.compute.amazonaws.com"
    port: 5000
    api_key: "your-secure-api-key"

# Cache configuration
cache:
  # Maximum age of cache entries in days (0 for no expiration)
  max_age: 30
  
  # Maximum entries in cache (0 for unlimited)
  max_entries: 10000