# Headnode Server Configuration

# API authentication
api_key: "your-secure-api-key"

# Server configuration
host: "0.0.0.0"
port: 5001
debug: True

# Worker node configuration
worker_nodes:
  - host: "ec2-3-17-191-215.us-east-2.compute.amazonaws.com"
    port: 5000
    api_key: "your-secure-api-key"
    high_ram: false

# Cache configuration
cache:
  # Maximum age of cache entries in days (0 for no expiration)
  max_age: 0
  
  # Maximum entries in cache (0 for unlimited)
  max_entries: 10000