name: unit tests


on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    test:
        runs-on: ubuntu-latest
        env:
            ENABLE_LOGGING: False
        defaults:
            run:
                working-directory: ./tests/
        strategy:
            matrix:
                os: [ubuntu-latest]
                python-version: [3.9]
        steps:
            - uses: actions/checkout@v4

            - name: Set up Python 3.9
              uses: actions/setup-python@v5
              with:
                python-version: ${{ matrix.python-version }}

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements_tests.txt
                
            - name: Run tests
              run: |
                pytest